#!/bin/bash

$VCS_REF=$(`git rev-parse —-short HEAD`)
$VERSION="v0.9.$VCS_REF"

docker build \
  --build-arg VCS_REF=${VCS_REF} \
  --build-arg VERSION=${VERSION} \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t $IMAGE_NAME .
